# 路点的模式：Pointmode {Takeoff_point , Detect_point, Nothing_point , Land_point};
#                            0             1             2                3 

# 单位：x(m), y(m), z(m), yaw(°), pointmode(Takeoff_point/Detect_point/Nothing_point/Land_point)
waypoints:
  - {x: 0.0, y: 0.0, z: 2.0, yaw: 0.0, pointmode: "Takeoff_point"} # takeoff，必须写在第一个
  - {x: 0.0, y: -3.0, z: 2.0, yaw: 0.0, pointmode: "Detect_point"}
  - {x: 3.0, y: -3.0, z: 2.0, yaw: 0.0, pointmode: "Detect_point"}
  #- {x: 0.0, y: 0.1, z: 0.5, yaw: 0.0, pointmode: "Nothing_point"} # land，必须写在最后一个
  - {x: 0.0, y: 0.0, z: 0.5, yaw: 0.0, pointmode: "Land_point"} # land，必须写在最后一个

land_height: 0.3                            #切入降落之前的高度，不要太高，也不能太小（太小容易与地面剐蹭）
px4_max_distance: 1.2                       #直接发送点位时，最大变化距离（直接给mavros发送点时决定最大速度）
max_yaw_change: 0.2                         #直接发送点位时，最大变化yaw

# threshould
threshould: 
  takeoff_threshould: 0.3                   #判断是否到达起飞点的阈值
  waypoint_threshould: 0.3                  #判断是否到达路点点的阈值
  aligning_threshould: 0.15                 #判断是否到达对准点的阈值
  landing_threshould: 0.15                  #判断是否到达降落点的阈值
  arrive_yaw_threshould: 0.3                #判断yaw是否到位的阈值

  planner_min_pub_threshould: 0.025         #限制往planner发送目标点的频率
  times_detect_threshould: 40               #路点为对准时，调整到位的次数阈值，判断次数大于这个阈值即认为已经对准
  waypoint_adjust_max_second_threshould: 20 #路点为对准时，最大调整时间阈值，超过阈值直接去下一个点
  land_adjust_max_second_threshould: 10     #路点为对准时，最大调整时间阈值，超过阈值直接降落

# bool switch
switch:
 flag_planner_px4: 0 # 0: planner   1: px4  ，设为0则使用planner在路点之间规划路径，设为1则使用直线在路点之间飞行
 flag_landing_detect: 0 # land detect flag  ，该标志位判断是否需要精确降落，0代表不检测，直接降落，1代表接收降落检测对准目标，对准之后再降落
 auto_land: 1 # auto_land flag  ，该标志位判断是否需要切入auto land, 0代表不使用autoland,直接发送高度为-1的点, 1代表使用auto land模式降落