waypoints:
  - {x: 0.00, y: 0.00, z: 0.80, yaw: 0.00, pointmode: "Takeoff_point", dwell_time: 0.0, gimbal_pitch: 0.0, cam_zoom: 1.0}
  - {x: 0.63, y: -0.79, z: 1.55, yaw: -90.00, pointmode: "Nothing_point", dwell_time: 0.0, gimbal_pitch: 0.0, cam_zoom: 1.0}
  - {x: 1.62, y: -0.79, z: 1.55, yaw: -90.00, pointmode: "Detect_point", dwell_time: 1.2, gimbal_pitch: 6.0, cam_zoom: 1.0}
  - {x: 2.62, y: -0.79, z: 1.55, yaw: -90.00, pointmode: "Detect_point", dwell_time: 1.2, gimbal_pitch: 6.0, cam_zoom: 1.0}
  - {x: 3.62, y: -0.79, z: 1.55, yaw: -90.00, pointmode: "Detect_point", dwell_time: 1.2, gimbal_pitch: 6.0, cam_zoom: 1.0}
  - {x: 3.62, y: -0.79, z: 0.50, yaw: -90.00, pointmode: "Detect_point", dwell_time: 1.2, gimbal_pitch: 6.0, cam_zoom: 1.0}
  - {x: 2.62, y: -0.79, z: 0.50, yaw: -90.00, pointmode: "Detect_point", dwell_time: 1.2, gimbal_pitch: 6.0, cam_zoom: 1.0}
  - {x: 1.62, y: -0.79, z: 0.50, yaw: -90.00, pointmode: "Detect_point", dwell_time: 1.2, gimbal_pitch: 6.0, cam_zoom: 1.0}
  - {x: 0.63, y: -0.79, z: 0.50, yaw: 90.00, pointmode: "Nothing_point", dwell_time: 0.0, gimbal_pitch: 0.0, cam_zoom: 1.0}
  - {x: 1.62, y: -0.79, z: 0.50, yaw: 90.00, pointmode: "Detect_point", dwell_time: 1.2, gimbal_pitch: 6.0, cam_zoom: 1.0}
  - {x: 2.62, y: -0.79, z: 0.50, yaw: 90.00, pointmode: "Detect_point", dwell_time: 1.2, gimbal_pitch: 6.0, cam_zoom: 1.0}
  - {x: 3.62, y: -0.79, z: 0.50, yaw: 90.00, pointmode: "Detect_point", dwell_time: 1.2, gimbal_pitch: 6.0, cam_zoom: 1.0}
  - {x: 3.62, y: -0.79, z: 1.55, yaw: 90.00, pointmode: "Detect_point", dwell_time: 1.2, gimbal_pitch: 6.0, cam_zoom: 1.0}
  - {x: 2.62, y: -0.79, z: 1.55, yaw: 90.00, pointmode: "Detect_point", dwell_time: 1.2, gimbal_pitch: 6.0, cam_zoom: 1.0}
  - {x: 1.62, y: -0.79, z: 1.55, yaw: 90.00, pointmode: "Detect_point", dwell_time: 1.2, gimbal_pitch: 6.0, cam_zoom: 1.0}
  - {x: 0.50, y: 0.00, z: 1.55, yaw: 90.00, pointmode: "Nothing_point", dwell_time: 0.0, gimbal_pitch: 0.0, cam_zoom: 1.0}
  - {x: 1.62, y: 1.43, z: 1.55, yaw: 90.00, pointmode: "Detect_point", dwell_time: 1.2, gimbal_pitch: 6.0, cam_zoom: 1.0}
  - {x: 2.62, y: 1.43, z: 1.55, yaw: 90.00, pointmode: "Detect_point", dwell_time: 1.2, gimbal_pitch: 6.0, cam_zoom: 1.0}
  - {x: 3.62, y: 1.43, z: 1.55, yaw: 90.00, pointmode: "Detect_point", dwell_time: 1.2, gimbal_pitch: 6.0, cam_zoom: 1.0}
  - {x: 3.62, y: 1.43, z: 0.50, yaw: 90.00, pointmode: "Detect_point", dwell_time: 1.2, gimbal_pitch: 6.0, cam_zoom: 1.0}
  - {x: 2.62, y: 1.43, z: 0.50, yaw: 90.00, pointmode: "Detect_point", dwell_time: 1.2, gimbal_pitch: 6.0, cam_zoom: 1.0}
  - {x: 1.62, y: 1.43, z: 0.50, yaw: 90.00, pointmode: "Detect_point", dwell_time: 1.2, gimbal_pitch: 6.0, cam_zoom: 1.0}
  - {x: 0.63, y: 1.43, z: 0.50, yaw: -90.00, pointmode: "Nothing_point", dwell_time: 0.0, gimbal_pitch: 0.0, cam_zoom: 1.0}
  - {x: 1.62, y: 1.43, z: 0.50, yaw: -90.00, pointmode: "Detect_point", dwell_time: 1.2, gimbal_pitch: 6.0, cam_zoom: 1.0}
  - {x: 2.62, y: 1.43, z: 0.50, yaw: -90.00, pointmode: "Detect_point", dwell_time: 1.2, gimbal_pitch: 6.0, cam_zoom: 1.0}
  - {x: 3.62, y: 1.43, z: 0.50, yaw: -90.00, pointmode: "Detect_point", dwell_time: 1.2, gimbal_pitch: 6.0, cam_zoom: 1.0}
  - {x: 3.62, y: 1.43, z: 1.55, yaw: -90.00, pointmode: "Detect_point", dwell_time: 1.2, gimbal_pitch: 6.0, cam_zoom: 1.0}
  - {x: 2.62, y: 1.43, z: 1.55, yaw: -90.00, pointmode: "Detect_point", dwell_time: 1.2, gimbal_pitch: 6.0, cam_zoom: 1.0}
  - {x: 1.62, y: 1.43, z: 1.55, yaw: -90.00, pointmode: "Detect_point", dwell_time: 1.2, gimbal_pitch: 6.0, cam_zoom: 1.0}
  - {x: 0.50, y: 0.00, z: 0.70, yaw: 0.00, pointmode: "Nothing_point", dwell_time: 0.0, gimbal_pitch: 0.0, cam_zoom: 1.0}
  - {x: 0.00, y: 0.00, z: 0.70, yaw: 0.00, pointmode: "Land_point", dwell_time: 1.0, gimbal_pitch: 0.0, cam_zoom: 1.0}
land_height: 0.2
px4_max_distance: 1.0
max_yaw_change: 0.2
threshould:
  takeoff_threshould: 0.3
  waypoint_threshould: 0.10
  aligning_threshould: 0.15
  landing_threshould: 0.15
  arrive_yaw_threshould: 0.3
  times_detect_threshould: 30
  waypoint_adjust_max_second_threshould: 5
  land_adjust_max_second_threshould: 10
  planner_cmd_stale_threshould: 0.3
  planner_min_pub_threshould: 0.02
switch:
  flag_planner_px4: 0
  flag_landing_detect: 0
  auto_land: 1
