// Generated by gencpp from file lidar_cam_fusion/EstimateDepthRequest.msg
// DO NOT EDIT!


#ifndef LIDAR_CAM_FUSION_MESSAGE_ESTIMATEDEPTHREQUEST_H
#define LIDAR_CAM_FUSION_MESSAGE_ESTIMATEDEPTHREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lidar_cam_fusion
{
template <class ContainerAllocator>
struct EstimateDepthRequest_
{
  typedef EstimateDepthRequest_<ContainerAllocator> Type;

  EstimateDepthRequest_()
    : u(0)
    , v(0)  {
    }
  EstimateDepthRequest_(const ContainerAllocator& _alloc)
    : u(0)
    , v(0)  {
  (void)_alloc;
    }



   typedef int32_t _u_type;
  _u_type u;

   typedef int32_t _v_type;
  _v_type v;





  typedef boost::shared_ptr< ::lidar_cam_fusion::EstimateDepthRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidar_cam_fusion::EstimateDepthRequest_<ContainerAllocator> const> ConstPtr;

}; // struct EstimateDepthRequest_

typedef ::lidar_cam_fusion::EstimateDepthRequest_<std::allocator<void> > EstimateDepthRequest;

typedef boost::shared_ptr< ::lidar_cam_fusion::EstimateDepthRequest > EstimateDepthRequestPtr;
typedef boost::shared_ptr< ::lidar_cam_fusion::EstimateDepthRequest const> EstimateDepthRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidar_cam_fusion::EstimateDepthRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidar_cam_fusion::EstimateDepthRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lidar_cam_fusion::EstimateDepthRequest_<ContainerAllocator1> & lhs, const ::lidar_cam_fusion::EstimateDepthRequest_<ContainerAllocator2> & rhs)
{
  return lhs.u == rhs.u &&
    lhs.v == rhs.v;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lidar_cam_fusion::EstimateDepthRequest_<ContainerAllocator1> & lhs, const ::lidar_cam_fusion::EstimateDepthRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lidar_cam_fusion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lidar_cam_fusion::EstimateDepthRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_cam_fusion::EstimateDepthRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_cam_fusion::EstimateDepthRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_cam_fusion::EstimateDepthRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_cam_fusion::EstimateDepthRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_cam_fusion::EstimateDepthRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidar_cam_fusion::EstimateDepthRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f06a7e8dd345ffb826d71a489782114b";
  }

  static const char* value(const ::lidar_cam_fusion::EstimateDepthRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf06a7e8dd345ffb8ULL;
  static const uint64_t static_value2 = 0x26d71a489782114bULL;
};

template<class ContainerAllocator>
struct DataType< ::lidar_cam_fusion::EstimateDepthRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidar_cam_fusion/EstimateDepthRequest";
  }

  static const char* value(const ::lidar_cam_fusion::EstimateDepthRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidar_cam_fusion::EstimateDepthRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request\n"
"int32 u\n"
"int32 v\n"
;
  }

  static const char* value(const ::lidar_cam_fusion::EstimateDepthRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidar_cam_fusion::EstimateDepthRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.u);
      stream.next(m.v);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EstimateDepthRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidar_cam_fusion::EstimateDepthRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lidar_cam_fusion::EstimateDepthRequest_<ContainerAllocator>& v)
  {
    s << indent << "u: ";
    Printer<int32_t>::stream(s, indent + "  ", v.u);
    s << indent << "v: ";
    Printer<int32_t>::stream(s, indent + "  ", v.v);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIDAR_CAM_FUSION_MESSAGE_ESTIMATEDEPTHREQUEST_H
