// Generated by gencpp from file lidar_cam_fusion/EstimateDepthResponse.msg
// DO NOT EDIT!


#ifndef LIDAR_CAM_FUSION_MESSAGE_ESTIMATEDEPTHRESPONSE_H
#define LIDAR_CAM_FUSION_MESSAGE_ESTIMATEDEPTHRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lidar_cam_fusion
{
template <class ContainerAllocator>
struct EstimateDepthResponse_
{
  typedef EstimateDepthResponse_<ContainerAllocator> Type;

  EstimateDepthResponse_()
    : depth(0.0)
    , success(false)
    , message()  {
    }
  EstimateDepthResponse_(const ContainerAllocator& _alloc)
    : depth(0.0)
    , success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef float _depth_type;
  _depth_type depth;

   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::lidar_cam_fusion::EstimateDepthResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidar_cam_fusion::EstimateDepthResponse_<ContainerAllocator> const> ConstPtr;

}; // struct EstimateDepthResponse_

typedef ::lidar_cam_fusion::EstimateDepthResponse_<std::allocator<void> > EstimateDepthResponse;

typedef boost::shared_ptr< ::lidar_cam_fusion::EstimateDepthResponse > EstimateDepthResponsePtr;
typedef boost::shared_ptr< ::lidar_cam_fusion::EstimateDepthResponse const> EstimateDepthResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidar_cam_fusion::EstimateDepthResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidar_cam_fusion::EstimateDepthResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lidar_cam_fusion::EstimateDepthResponse_<ContainerAllocator1> & lhs, const ::lidar_cam_fusion::EstimateDepthResponse_<ContainerAllocator2> & rhs)
{
  return lhs.depth == rhs.depth &&
    lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lidar_cam_fusion::EstimateDepthResponse_<ContainerAllocator1> & lhs, const ::lidar_cam_fusion::EstimateDepthResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lidar_cam_fusion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lidar_cam_fusion::EstimateDepthResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_cam_fusion::EstimateDepthResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_cam_fusion::EstimateDepthResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_cam_fusion::EstimateDepthResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_cam_fusion::EstimateDepthResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_cam_fusion::EstimateDepthResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidar_cam_fusion::EstimateDepthResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73b7aa5fd6d61663d80e18f7243b5da5";
  }

  static const char* value(const ::lidar_cam_fusion::EstimateDepthResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73b7aa5fd6d61663ULL;
  static const uint64_t static_value2 = 0xd80e18f7243b5da5ULL;
};

template<class ContainerAllocator>
struct DataType< ::lidar_cam_fusion::EstimateDepthResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidar_cam_fusion/EstimateDepthResponse";
  }

  static const char* value(const ::lidar_cam_fusion::EstimateDepthResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidar_cam_fusion::EstimateDepthResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response\n"
"float32 depth\n"
"bool success\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::lidar_cam_fusion::EstimateDepthResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidar_cam_fusion::EstimateDepthResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.depth);
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EstimateDepthResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidar_cam_fusion::EstimateDepthResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lidar_cam_fusion::EstimateDepthResponse_<ContainerAllocator>& v)
  {
    s << indent << "depth: ";
    Printer<float>::stream(s, indent + "  ", v.depth);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIDAR_CAM_FUSION_MESSAGE_ESTIMATEDEPTHRESPONSE_H
