// Generated by gencpp from file lidar_cam_fusion/EstimateDepth.msg
// DO NOT EDIT!


#ifndef LIDAR_CAM_FUSION_MESSAGE_ESTIMATEDEPTH_H
#define LIDAR_CAM_FUSION_MESSAGE_ESTIMATEDEPTH_H

#include <ros/service_traits.h>


#include <lidar_cam_fusion/EstimateDepthRequest.h>
#include <lidar_cam_fusion/EstimateDepthResponse.h>


namespace lidar_cam_fusion
{

struct EstimateDepth
{

typedef EstimateDepthRequest Request;
typedef EstimateDepthResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EstimateDepth
} // namespace lidar_cam_fusion


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lidar_cam_fusion::EstimateDepth > {
  static const char* value()
  {
    return "6b0b4ebac49f6f6495d02adaa373af68";
  }

  static const char* value(const ::lidar_cam_fusion::EstimateDepth&) { return value(); }
};

template<>
struct DataType< ::lidar_cam_fusion::EstimateDepth > {
  static const char* value()
  {
    return "lidar_cam_fusion/EstimateDepth";
  }

  static const char* value(const ::lidar_cam_fusion::EstimateDepth&) { return value(); }
};


// service_traits::MD5Sum< ::lidar_cam_fusion::EstimateDepthRequest> should match
// service_traits::MD5Sum< ::lidar_cam_fusion::EstimateDepth >
template<>
struct MD5Sum< ::lidar_cam_fusion::EstimateDepthRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lidar_cam_fusion::EstimateDepth >::value();
  }
  static const char* value(const ::lidar_cam_fusion::EstimateDepthRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lidar_cam_fusion::EstimateDepthRequest> should match
// service_traits::DataType< ::lidar_cam_fusion::EstimateDepth >
template<>
struct DataType< ::lidar_cam_fusion::EstimateDepthRequest>
{
  static const char* value()
  {
    return DataType< ::lidar_cam_fusion::EstimateDepth >::value();
  }
  static const char* value(const ::lidar_cam_fusion::EstimateDepthRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lidar_cam_fusion::EstimateDepthResponse> should match
// service_traits::MD5Sum< ::lidar_cam_fusion::EstimateDepth >
template<>
struct MD5Sum< ::lidar_cam_fusion::EstimateDepthResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lidar_cam_fusion::EstimateDepth >::value();
  }
  static const char* value(const ::lidar_cam_fusion::EstimateDepthResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lidar_cam_fusion::EstimateDepthResponse> should match
// service_traits::DataType< ::lidar_cam_fusion::EstimateDepth >
template<>
struct DataType< ::lidar_cam_fusion::EstimateDepthResponse>
{
  static const char* value()
  {
    return DataType< ::lidar_cam_fusion::EstimateDepth >::value();
  }
  static const char* value(const ::lidar_cam_fusion::EstimateDepthResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIDAR_CAM_FUSION_MESSAGE_ESTIMATEDEPTH_H
