// Generated by gencpp from file pixel2map/PredictResult.msg
// DO NOT EDIT!


#ifndef PIXEL2MAP_MESSAGE_PREDICTRESULT_H
#define PIXEL2MAP_MESSAGE_PREDICTRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pixel2map
{
template <class ContainerAllocator>
struct PredictResult_
{
  typedef PredictResult_<ContainerAllocator> Type;

  PredictResult_()
    : classes_num()
    , classes_name()
    , confidence()
    , centre_x()
    , centre_y()
    , width()
    , height()
    , top_left_x()
    , top_left_y()
    , bottom_right_x()
    , bottom_right_y()  {
    }
  PredictResult_(const ContainerAllocator& _alloc)
    : classes_num(_alloc)
    , classes_name(_alloc)
    , confidence(_alloc)
    , centre_x(_alloc)
    , centre_y(_alloc)
    , width(_alloc)
    , height(_alloc)
    , top_left_x(_alloc)
    , top_left_y(_alloc)
    , bottom_right_x(_alloc)
    , bottom_right_y(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int8_t>> _classes_num_type;
  _classes_num_type classes_num;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _classes_name_type;
  _classes_name_type classes_name;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _confidence_type;
  _confidence_type confidence;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _centre_x_type;
  _centre_x_type centre_x;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _centre_y_type;
  _centre_y_type centre_y;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _width_type;
  _width_type width;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _height_type;
  _height_type height;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _top_left_x_type;
  _top_left_x_type top_left_x;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _top_left_y_type;
  _top_left_y_type top_left_y;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _bottom_right_x_type;
  _bottom_right_x_type bottom_right_x;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _bottom_right_y_type;
  _bottom_right_y_type bottom_right_y;





  typedef boost::shared_ptr< ::pixel2map::PredictResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pixel2map::PredictResult_<ContainerAllocator> const> ConstPtr;

}; // struct PredictResult_

typedef ::pixel2map::PredictResult_<std::allocator<void> > PredictResult;

typedef boost::shared_ptr< ::pixel2map::PredictResult > PredictResultPtr;
typedef boost::shared_ptr< ::pixel2map::PredictResult const> PredictResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pixel2map::PredictResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pixel2map::PredictResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pixel2map::PredictResult_<ContainerAllocator1> & lhs, const ::pixel2map::PredictResult_<ContainerAllocator2> & rhs)
{
  return lhs.classes_num == rhs.classes_num &&
    lhs.classes_name == rhs.classes_name &&
    lhs.confidence == rhs.confidence &&
    lhs.centre_x == rhs.centre_x &&
    lhs.centre_y == rhs.centre_y &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.top_left_x == rhs.top_left_x &&
    lhs.top_left_y == rhs.top_left_y &&
    lhs.bottom_right_x == rhs.bottom_right_x &&
    lhs.bottom_right_y == rhs.bottom_right_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pixel2map::PredictResult_<ContainerAllocator1> & lhs, const ::pixel2map::PredictResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pixel2map

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pixel2map::PredictResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pixel2map::PredictResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pixel2map::PredictResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pixel2map::PredictResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pixel2map::PredictResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pixel2map::PredictResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pixel2map::PredictResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "352e2a57f7bb0d5c224a46b492ed8655";
  }

  static const char* value(const ::pixel2map::PredictResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x352e2a57f7bb0d5cULL;
  static const uint64_t static_value2 = 0x224a46b492ed8655ULL;
};

template<class ContainerAllocator>
struct DataType< ::pixel2map::PredictResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pixel2map/PredictResult";
  }

  static const char* value(const ::pixel2map::PredictResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pixel2map::PredictResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8[] classes_num\n"
"string[] classes_name\n"
"float32[] confidence\n"
"float32[] centre_x\n"
"float32[] centre_y\n"
"float32[] width\n"
"float32[] height\n"
"float32[] top_left_x\n"
"float32[] top_left_y\n"
"float32[] bottom_right_x\n"
"float32[] bottom_right_y\n"
;
  }

  static const char* value(const ::pixel2map::PredictResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pixel2map::PredictResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.classes_num);
      stream.next(m.classes_name);
      stream.next(m.confidence);
      stream.next(m.centre_x);
      stream.next(m.centre_y);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.top_left_x);
      stream.next(m.top_left_y);
      stream.next(m.bottom_right_x);
      stream.next(m.bottom_right_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PredictResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pixel2map::PredictResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pixel2map::PredictResult_<ContainerAllocator>& v)
  {
    s << indent << "classes_num[]" << std::endl;
    for (size_t i = 0; i < v.classes_num.size(); ++i)
    {
      s << indent << "  classes_num[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.classes_num[i]);
    }
    s << indent << "classes_name[]" << std::endl;
    for (size_t i = 0; i < v.classes_name.size(); ++i)
    {
      s << indent << "  classes_name[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.classes_name[i]);
    }
    s << indent << "confidence[]" << std::endl;
    for (size_t i = 0; i < v.confidence.size(); ++i)
    {
      s << indent << "  confidence[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.confidence[i]);
    }
    s << indent << "centre_x[]" << std::endl;
    for (size_t i = 0; i < v.centre_x.size(); ++i)
    {
      s << indent << "  centre_x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.centre_x[i]);
    }
    s << indent << "centre_y[]" << std::endl;
    for (size_t i = 0; i < v.centre_y.size(); ++i)
    {
      s << indent << "  centre_y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.centre_y[i]);
    }
    s << indent << "width[]" << std::endl;
    for (size_t i = 0; i < v.width.size(); ++i)
    {
      s << indent << "  width[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.width[i]);
    }
    s << indent << "height[]" << std::endl;
    for (size_t i = 0; i < v.height.size(); ++i)
    {
      s << indent << "  height[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.height[i]);
    }
    s << indent << "top_left_x[]" << std::endl;
    for (size_t i = 0; i < v.top_left_x.size(); ++i)
    {
      s << indent << "  top_left_x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.top_left_x[i]);
    }
    s << indent << "top_left_y[]" << std::endl;
    for (size_t i = 0; i < v.top_left_y.size(); ++i)
    {
      s << indent << "  top_left_y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.top_left_y[i]);
    }
    s << indent << "bottom_right_x[]" << std::endl;
    for (size_t i = 0; i < v.bottom_right_x.size(); ++i)
    {
      s << indent << "  bottom_right_x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.bottom_right_x[i]);
    }
    s << indent << "bottom_right_y[]" << std::endl;
    for (size_t i = 0; i < v.bottom_right_y.size(); ++i)
    {
      s << indent << "  bottom_right_y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.bottom_right_y[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIXEL2MAP_MESSAGE_PREDICTRESULT_H
