#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL (Vision)
#
# @type Quadrotor Wide
#

. ${R}etc/init.d-posix/airframes/10015_gazebo-classic_iris

# EKF2: Vision position and heading, no GPS
param set-default EKF2_EV_DELAY 5
param set-default EKF2_EV_CTRL 15
param set-default EKF2_HGT_REF 3
param set-default EKF2_GPS_CTRL 0
param set-default SYS_HAS_MAG 0
param set-default COM_RC_IN_MODE 1