
# just for visualization  与探索算法完全无关
# in frontier_manager  clouds2ikdtree.cpp
clouds2ikdtree:
  # global clouds input  
  pointcloud_topic: "/freedom/static_pointcloud"
  odom_topic: "/mavros/local_position/odom"  # /quad_0/lidar_slam/odom
  
  explore_finish_trigger: "/explore_finish" 
  
  pub_map_topic: "/global_ikdtree_map"
  ikdtree_res: 0.15 # 地图下采样率
  pub_odom_topic: "/explored/path" 
  save_pcd: true  # for marsim 
  file_name: "demo.pcd"

